[build]
  publish = ""
  functions = "functions"

# Automatische Redirects
[[redirects]]
  from = "/*"
  to = "/blocked"
  status = 403
  force = true

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/index.html"
  to = "/index.html"
  status = 200
  force = true
  
[[redirects]]
  from = "/main.html"
  to = "/main.html"
  status = 200
  force = true
  
[[edge_functions]]
  function = "auth"
  path = "/*"